### PR TITLE
Update colors

### LINKED ISSUE #89: Colour updates
Final colours the design team settled on (https://github.com/MozillaFoundation/Design/issues/139) are slightly different than what appears on the [demo page](https://mozilla.github.io/mofo-bootstrap/demo/).

We have https://redpen.io/aq798f74c9a3ad7266
red-pen-795c21c7-82b8-4e28-e37d-2868c2c4a7fe

**How we came to get those colours:**
We adjusted the base hex values and then used LESS to create the three other tints of that same colour. 

Luke created a handy tool to test out the colours http://flukeout.github.io/color-generator/
and http://flukeout.github.io/master-template/style-guide/?theme=theme-march-14

For Sketch files, we then ink dropped the generated tints to get the hex values.

We also found we needed more grey tints.

**Question:**
@gvn @alanmoo how were the colours on the demo page generated? Are you using opacity? Does it make sense to update mofo-bootstrap so it generates colours using LESS?

cc @sabrinang @taisdesouzalessa

### PR DESCRIPTION
**Pull request by alanmoo**
Still need greys. Closes #89

### CODE REVIEW

**Comment by alanmoo** [comment]
@mmmavis Once this is approved, it should have the colors and grays needed from the designs for the footer and other projects going forward.

cc @kristinashu

**Comment by alanmoo** [comment]
@gvn Not sure if this should be a major or minor point release. Thoughts?

**Comment by gvn** [comment]
Probably minor? All the changes are additive, right?

**Comment by alanmoo** [comment]
Technically $charcoal isn't in there anymore. I believe that's it. Maybe I could leave it as "deprecated"?

**Comment by alanmoo** [comment]
Scratch that, it's still there. I just dropped it from the guide

**Comment by gvn** [comment]
Yeah, lets leave that in there but add a deprecation comment.

**Comment by alanmoo** [comment]
Added the comment. Merging

**Pull request merged**
