### PR TITLE
Added footer icon cookies

### LINKED ISSUE #100: Missing one footer icon
https://github.com/mozilla/mofo-bootstrap/issues/92#issuecomment-272573805
the cookie icon 🍪

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #100

### CODE REVIEW

**Comment by mmmavis** [comment]
☕️ 🍪 ☕️

**Comment by mmmavis** [comment]
@gvn I updated this PR with link to the cookies section on mozilla.org privacy page.

**Comment by mmmavis** [comment]
@gvn wanna merge and push a new version out? 🍪

**Comment by gvn** [comment]
Totes! `3.2.0` is now published with 🍪

**Pull request merged**
