### PR TITLE
Various Improvements

### PR DESCRIPTION
**Pull request by Mte90**
About index:
- Added navbar
- Added forms
- The buttons are in two column to improve the UX
- Fixed the Color box alignment

About _navbar.scss:
- file added
- little fix about alignment for navbar-header

### CODE REVIEW

**Comment by Mte90** [comment]
any updates?

**Comment by Mte90** [comment]
bump

**Comment by alanmoo** [comment]
Hey @Mte90 I just saw this. We've made some not-insignificant changes lately, if you can do a quick rebase I'll take a look at this. If it's more than a simple rebase though, let's discuss what you're looking to add here and make sure it aligns with the goals of this project.

**Comment by Mte90** [comment]
Well i not remember so much but my edits was to add support for other components of bootstrap to that theme and improve the demo page with this new components.
I can look it to rebase but not asap.

**Comment by alanmoo** [comment]
We're taking a bit of a different approach here so components may not be appropriate for this repo- we're mainly using Bootstrap for style here, and building components in https://github.com/mozilla/mofo-ui.

**Comment by Mte90** [comment]
With component I was talking about html component of bootstrap :-)

**Comment by Mte90** [comment]
Closing because there is a new version and I have no time to backporting

**Pull request closed without merging**
