### PR TITLE
Demo->Docs

### PR DESCRIPTION
**Pull request by alanmoo**
For easier gh-pages deployment. Once this is merged, the repo can just point to the docs folder (using the repo settings in github) for the example page. Should I also remove deploy.js?

### CODE REVIEW

**Comment by gvn** [comment]
I don't want to put compiled files into `master`.

I'm planning to refactor the `version` scripts, and part of that will be auto-deploying the demo as a postversion command. That will mean the demo will always match the currently published npm package instead of latest master, which I feel is best since library users should be using a versioned release instead of pointing to latest master.

**Comment by alanmoo** [comment]
Ah, that makes sense. Should I just open a PR for the Travis fix then?

**Comment by gvn** [comment]
I think my removal of nodegit will actually fix Travis too...

**Comment by alanmoo** [comment]
Yeah, for now it probably will, but it would be best to avoid this in the future, no? If we're version locking everything, why not also lock the version of node we're testing with to a major version?

**Comment by gvn** [comment]
I guess I could go either way. Travis is kind of a nice canary in the coalmine I guess? I feel like we should always make sure things work with latest Node.

**Comment by alanmoo** [comment]
Ah, that's a pretty reasonable point.

**Pull request closed without merging**
