### PR TITLE
Updated footer's background colour to black

### LINKED ISSUE #112: Update footer's background colour from $gray-dark to $black
@kristinashu mentioned 

> [New Mozilla brand](https://mozilla.ninja/) uses black instead of dark grey. We need to update the and the footer to black.

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #112

### CODE REVIEW

**Comment by alanmoo** [comment]
I hesitate to ask this because I don't want to go down a rabbit hole, but shouldn't we update all the colors at once as a major release?

**Comment by mmmavis** [comment]
Um I don't know how different the new branding is from before. If colours differ drastically we should probably update them all as a major release. Thoughts @kristinashu ?

**Comment by alanmoo** [comment]
(I'm also not sure how much the current builds of pulse and the network site rely on mofo-bootstrap colors, so the usefulness of an involved upgrade is questionable.)

**Comment by kristinashu** [comment]
The full color palette will be a long time away and I think a little more flexible. The dark grey to black is a clear and quick win for now.

**Comment by alanmoo** [comment]
I don't disagree, but is the color pallet going to continue to change from https://mozilla.ninja/visualelements?

**Comment by kristinashu** [comment]
Yes, that palette has been really hard to work with so I believe they will be iterating on it (hopefully?).

**Pull request merged**
